language: java

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "sonarqubesecurity1"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean verify sonar:sonar \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.organization=sonarqubesecurity1 \
      -Dsonar.projectKey=com.ipiecoles.java:java350
